### ISSUE TITLE
Error "Expect type list" when "fields" parameter is populated

### ISSUE THREAD

**Issue by MattCloward** [biothings/myvariant.py#12]
I am trying to run the following code. A few weeks ago it was working, but now I get an error every time I run it. I also tried making the fields variable a list, using only one field, and having no fields. All those options gave me the same error except the no fields option.

```
rsID = 'rs1466535'
queryResult = mv.query('dbsnp.rsid:{}'.format(rsID), fields='dbsnp.alleles.allele, dbsnp.dbsnp_merges, dbsnp.gene.strand, dbsnp.alt, dbsnp.ref')
```

Here is the error I got:
```
Traceback (most recent call last):
  File "myFile.py", line 19, in myFunc
    queryResult = mv.query('dbsnp.rsid:{}'.format(rsID), fields=['dbsnp.alleles.allele', 'dbsnp.dbsnp_merges', 'dbsnp.gene.strand', 'dbsnp.alt', 
'dbsnp.ref'])
  File "/home/username/.local/lib/python3.8/site-packages/biothings_client/base.py", line 445, in _query
    from_cache, out = self._get(_url, kwargs, verbose=verbose)
  File "/home/username/.local/lib/python3.8/site-packages/biothings_client/base.py", line 163, in _get
    res.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Expect type list. for url: http://myvariant.info/v1/query/
```
Am I doing something wrong, or is this a problem with myvariant?
Thank you!

**Comment by newgene** [comment]
@MattCloward most likely its underlying `biothings_client` package needs to be updated. 

```
pip install biothings_client -U
```

should bring it back to work.

**Comment by MattCloward** [comment]
That did work, thank you very much!
